logging:
  level: INFO
  loggers:
    timely: DEBUG
 
    timely.tasks: DEBUG  

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
